version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: cmd/beeline/Dockerfile
    container_name: beeline
    ports:
      - '8080:8080'
    networks:
      - beeline
    restart: always

networks:
  beeline:
    driver: bridge
